### PR TITLE
Explicitly allow labelledby to be passed to react-bootstrap-slider

### PR DESCRIPTION
**Pull request by yefim**

### CODE REVIEW

**Comment by brownieboy** [comment]
Thanks for this.

You've typed labelledby as a string here, but according to Seiyria's it could be either an array or a string.  There's `oneOfType` method in PropTypes that should allow you to do this.  I guess the syntax would be something like:

```
labelledby: PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.arrayOf(PropTypes.string)
]),
```

I've not tested this though.

**Comment by yefim** [comment]
Sounds good. Will update!

**Comment by yefim** [comment]
@brownieboy updated!

**Comment by brownieboy** [comment]
Okay, I'll get this merged soon.

**Comment by yefim** [comment]
Thanks!

**Comment by brownieboy** [comment]
All tests passed.

Merged with Master branch and published as version npmjs as version 2.1.4.

**Pull request merged**
